public class Main {
    public static void main(String[] args) {

        System.out.println("****C026-01-0726/2023****");
        System.out.println("#99 ACS Building Gilmore Ave.New Mla..Quezon city * Tel no 123-456");
        System.out.println("VAT.REG  TIN 098-765-4321-0000");
        System.out.println(" SALES INVOICE");
        System.out.println("SOLD TO:Chomba Gitari\t\t Date:2/10/24");
        System.out.println("Address:00232\t\t CONT NUMBER:0722345679\n\n");
        System.out.println("QTY\t ITEM DESCRIPTION\t UNIT PRICE\t AMOUNT");
        System.out.println("4\t pencil\t 20\t 80");
        System.out.println("10\t DUSTER\t 50\t 500");
        System.out.println(" \t \t subtotal\t 580");
        System.out.println("\t \t VAT(16%)\t ");
        System.out.println(" \t \t TOTAL AMOUNT");
    }
}
